/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.DB4OUtil.DB4OUtil;
import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import userInterface.SystemAdmin.SystemAdminJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javafx.scene.control.SplitPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Ankit
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
     private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        this.setExtendedState(MAXIMIZED_BOTH);
        btnLogout.setVisible(false);
        DateFormat day = new SimpleDateFormat("E");
        DateFormat df = new SimpleDateFormat("MM/dd");
        
        Calendar calender = Calendar.getInstance();
        
        txtDay1.setText(df.format(calender.getTime()));
        calender.add( Calendar.DATE, 1 );
         txtDay2.setText(df.format(calender.getTime()));
         calender.add( Calendar.DATE, 1 );
         txtDay3.setText(df.format(calender.getTime()));
         calender.add( Calendar.DATE, 1 );
         txtDay4.setText(df.format(calender.getTime()));
         calender.add( Calendar.DATE, 1 );
         txtDay5.setText(df.format(calender.getTime()));
         calender.add( Calendar.DATE, 1 );
         txtDay6.setText(df.format(calender.getTime()));
         calender.add( Calendar.DATE, 1 );
         txtDay7.setText(df.format(calender.getTime()));
         
         
         //code for pupulation the schedule table under doctor availability tab
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanelTop = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        lblPassWord = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        container = new javax.swing.JPanel();
        jTabbedPanel = new javax.swing.JTabbedPane();
        jPanelDoctorAvailability = new javax.swing.JPanel();
        jPanelDoctorsAvailability = new javax.swing.JPanel();
        txtDay1Slot1 = new javax.swing.JTextField();
        txtDay2Slot1 = new javax.swing.JTextField();
        txtDay3Slot1 = new javax.swing.JTextField();
        txtDay4Slot1 = new javax.swing.JTextField();
        txtDay5Slot1 = new javax.swing.JTextField();
        txtDay6Slot1 = new javax.swing.JTextField();
        txtDay7Slot1 = new javax.swing.JTextField();
        txtSlot1 = new javax.swing.JTextField();
        txtDay7Slot2 = new javax.swing.JTextField();
        txtSlot2 = new javax.swing.JTextField();
        txtDay1Slot2 = new javax.swing.JTextField();
        txtDay2Slot2 = new javax.swing.JTextField();
        txtDay3Slot2 = new javax.swing.JTextField();
        txtDay4Slot2 = new javax.swing.JTextField();
        txtDay7Slot3 = new javax.swing.JTextField();
        txtSlot3 = new javax.swing.JTextField();
        txtDay1Slot3 = new javax.swing.JTextField();
        txtDay2Slot3 = new javax.swing.JTextField();
        txtDay3Day3 = new javax.swing.JTextField();
        txtDay7Slot4 = new javax.swing.JTextField();
        txtSlot4 = new javax.swing.JTextField();
        txtDay1Slot4 = new javax.swing.JTextField();
        txtDay2Slot4 = new javax.swing.JTextField();
        txtDay3Slot4 = new javax.swing.JTextField();
        txtDay7Slot5 = new javax.swing.JTextField();
        txtSlot5 = new javax.swing.JTextField();
        txtDay1Slot5 = new javax.swing.JTextField();
        txtDay2Slot5 = new javax.swing.JTextField();
        txtDay3Slot5 = new javax.swing.JTextField();
        txtDay7Slot6 = new javax.swing.JTextField();
        txtSlot6 = new javax.swing.JTextField();
        txtDay1Slot6 = new javax.swing.JTextField();
        txtDay2Slot6 = new javax.swing.JTextField();
        txtDay3Slot6 = new javax.swing.JTextField();
        txtDay7Slot7 = new javax.swing.JTextField();
        txtSlot7 = new javax.swing.JTextField();
        txtDay1Slot7 = new javax.swing.JTextField();
        txtDay2Slot7 = new javax.swing.JTextField();
        txtDay3Slot7 = new javax.swing.JTextField();
        txtDay7Slot8 = new javax.swing.JTextField();
        txtSlot8 = new javax.swing.JTextField();
        txtDay1Slot8 = new javax.swing.JTextField();
        txtDay2Slot8 = new javax.swing.JTextField();
        txtDay3Slot8 = new javax.swing.JTextField();
        txtDay7Slot9 = new javax.swing.JTextField();
        txtSlot9 = new javax.swing.JTextField();
        txtDay1Slot9 = new javax.swing.JTextField();
        txtDay2Slot9 = new javax.swing.JTextField();
        txtDay3Slot9 = new javax.swing.JTextField();
        txtDay7 = new javax.swing.JTextField();
        txtDaySlot = new javax.swing.JTextField();
        txtDay1 = new javax.swing.JTextField();
        txtDay2 = new javax.swing.JTextField();
        txtDay3 = new javax.swing.JTextField();
        txtDay4 = new javax.swing.JTextField();
        txtDay5 = new javax.swing.JTextField();
        txtDay6 = new javax.swing.JTextField();
        txtDay4Slot3 = new javax.swing.JTextField();
        txtDay4Slot4 = new javax.swing.JTextField();
        txtDay4Slot5 = new javax.swing.JTextField();
        txtDay4Slot6 = new javax.swing.JTextField();
        txtDay4Slot7 = new javax.swing.JTextField();
        txtDay4Slot8 = new javax.swing.JTextField();
        txtDay4Slot9 = new javax.swing.JTextField();
        txtDay5Slot2 = new javax.swing.JTextField();
        txtDay5Slot3 = new javax.swing.JTextField();
        txtDay5Slot4 = new javax.swing.JTextField();
        txtDay5Slot5 = new javax.swing.JTextField();
        txtDay5Slot6 = new javax.swing.JTextField();
        txtDay5Slot7 = new javax.swing.JTextField();
        txtDay5Slot8 = new javax.swing.JTextField();
        txtDay5Slot9 = new javax.swing.JTextField();
        txtDay6Slot2 = new javax.swing.JTextField();
        txtDay6Slot3 = new javax.swing.JTextField();
        txtDay6Slot4 = new javax.swing.JTextField();
        txtDay6Slot5 = new javax.swing.JTextField();
        txtDay6Slot6 = new javax.swing.JTextField();
        txtDay6Slot7 = new javax.swing.JTextField();
        txtDay6Slot8 = new javax.swing.JTextField();
        txtDay6Slot9 = new javax.swing.JTextField();
        jPanel_About = new javax.swing.JPanel();
        jPanelPharmacy = new javax.swing.JPanel();
        jPanelEmergency = new javax.swing.JPanel();
        jPanelRegistration = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        streetAddressLine1TextField = new javax.swing.JTextField();
        streetAddressLine2TextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane.setDividerLocation(150);
        jSplitPane.setDividerSize(0);
        jSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanelTop.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/herblogo.png"))); // NOI18N

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserNameFocusGained(evt);
            }
        });
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        lblUserName.setText("USERNAME:");

        lblPassWord.setText("PASSWORD: ");

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 650, Short.MAX_VALUE)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassWord, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUserName)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo)
                    .addGroup(jPanelTopLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnLogin))))
                .addGap(22, 22, 22))
        );

        jSplitPane.setTopComponent(jPanelTop);

        container.setLayout(new java.awt.CardLayout());

        jTabbedPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanelDoctorAvailability.setBackground(new java.awt.Color(255, 255, 255));

        jPanelDoctorsAvailability.setBackground(new java.awt.Color(104, 120, 128));

        txtDay1Slot1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay1Slot1.setEnabled(false);
        txtDay1Slot1.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay2Slot1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay2Slot1.setEnabled(false);
        txtDay2Slot1.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay3Slot1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay3Slot1.setEnabled(false);
        txtDay3Slot1.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay4Slot1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay4Slot1.setEnabled(false);
        txtDay4Slot1.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay5Slot1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay5Slot1.setEnabled(false);
        txtDay5Slot1.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay6Slot1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay6Slot1.setEnabled(false);
        txtDay6Slot1.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay7Slot1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay7Slot1.setEnabled(false);
        txtDay7Slot1.setMinimumSize(new java.awt.Dimension(100, 22));

        txtSlot1.setText("9:00-10:00AM");
        txtSlot1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSlot1.setEnabled(false);
        txtSlot1.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay7Slot2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay7Slot2.setEnabled(false);
        txtDay7Slot2.setMinimumSize(new java.awt.Dimension(100, 22));

        txtSlot2.setText("10:00-11:00AM");
        txtSlot2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSlot2.setEnabled(false);
        txtSlot2.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay1Slot2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay1Slot2.setEnabled(false);
        txtDay1Slot2.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay2Slot2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay2Slot2.setEnabled(false);
        txtDay2Slot2.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay3Slot2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay3Slot2.setEnabled(false);
        txtDay3Slot2.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay4Slot2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay4Slot2.setEnabled(false);
        txtDay4Slot2.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay7Slot3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay7Slot3.setEnabled(false);
        txtDay7Slot3.setMinimumSize(new java.awt.Dimension(100, 22));

        txtSlot3.setText("11:00-12:00PM");
        txtSlot3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSlot3.setEnabled(false);
        txtSlot3.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay1Slot3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay1Slot3.setEnabled(false);
        txtDay1Slot3.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay2Slot3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay2Slot3.setEnabled(false);
        txtDay2Slot3.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay3Day3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay3Day3.setEnabled(false);
        txtDay3Day3.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay7Slot4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay7Slot4.setEnabled(false);
        txtDay7Slot4.setMinimumSize(new java.awt.Dimension(100, 22));

        txtSlot4.setText("12:00-1:00PM");
        txtSlot4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSlot4.setEnabled(false);
        txtSlot4.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay1Slot4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay1Slot4.setEnabled(false);
        txtDay1Slot4.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay2Slot4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay2Slot4.setEnabled(false);
        txtDay2Slot4.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay3Slot4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay3Slot4.setEnabled(false);
        txtDay3Slot4.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay7Slot5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay7Slot5.setEnabled(false);
        txtDay7Slot5.setMinimumSize(new java.awt.Dimension(100, 22));

        txtSlot5.setText("1:00-2:00PM");
        txtSlot5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSlot5.setEnabled(false);
        txtSlot5.setMinimumSize(new java.awt.Dimension(100, 22));
        txtSlot5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSlot5ActionPerformed(evt);
            }
        });

        txtDay1Slot5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay1Slot5.setEnabled(false);
        txtDay1Slot5.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay2Slot5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay2Slot5.setEnabled(false);
        txtDay2Slot5.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay3Slot5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay3Slot5.setEnabled(false);
        txtDay3Slot5.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay7Slot6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay7Slot6.setEnabled(false);
        txtDay7Slot6.setMinimumSize(new java.awt.Dimension(100, 22));

        txtSlot6.setText("2:00-3:00PM");
        txtSlot6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSlot6.setEnabled(false);
        txtSlot6.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay1Slot6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay1Slot6.setEnabled(false);
        txtDay1Slot6.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay2Slot6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay2Slot6.setEnabled(false);
        txtDay2Slot6.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay3Slot6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay3Slot6.setEnabled(false);
        txtDay3Slot6.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay7Slot7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay7Slot7.setEnabled(false);
        txtDay7Slot7.setMinimumSize(new java.awt.Dimension(100, 22));

        txtSlot7.setText("3:00-4:00PM");
        txtSlot7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSlot7.setEnabled(false);
        txtSlot7.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay1Slot7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay1Slot7.setEnabled(false);
        txtDay1Slot7.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay2Slot7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay2Slot7.setEnabled(false);
        txtDay2Slot7.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay3Slot7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay3Slot7.setEnabled(false);
        txtDay3Slot7.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay7Slot8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay7Slot8.setEnabled(false);
        txtDay7Slot8.setMinimumSize(new java.awt.Dimension(100, 22));

        txtSlot8.setText("4:00-5:00PM");
        txtSlot8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSlot8.setEnabled(false);
        txtSlot8.setMinimumSize(new java.awt.Dimension(100, 22));
        txtSlot8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSlot8ActionPerformed(evt);
            }
        });

        txtDay1Slot8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay1Slot8.setEnabled(false);
        txtDay1Slot8.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay2Slot8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay2Slot8.setEnabled(false);
        txtDay2Slot8.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay3Slot8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay3Slot8.setEnabled(false);
        txtDay3Slot8.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay7Slot9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay7Slot9.setEnabled(false);
        txtDay7Slot9.setMinimumSize(new java.awt.Dimension(100, 22));

        txtSlot9.setText("5:00-6:00PM");
        txtSlot9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSlot9.setEnabled(false);
        txtSlot9.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay1Slot9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay1Slot9.setEnabled(false);
        txtDay1Slot9.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay2Slot9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay2Slot9.setEnabled(false);
        txtDay2Slot9.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay3Slot9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay3Slot9.setEnabled(false);
        txtDay3Slot9.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDay7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay7.setEnabled(false);
        txtDay7.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDaySlot.setText("TIME/DAY");
        txtDaySlot.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDaySlot.setEnabled(false);
        txtDaySlot.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDay1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay1.setEnabled(false);
        txtDay1.setMinimumSize(new java.awt.Dimension(100, 22));
        txtDay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDay1ActionPerformed(evt);
            }
        });

        txtDay2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDay2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay2.setEnabled(false);
        txtDay2.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDay3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay3.setEnabled(false);
        txtDay3.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDay4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay4.setEnabled(false);
        txtDay4.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDay5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay5.setEnabled(false);
        txtDay5.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDay6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay6.setEnabled(false);
        txtDay6.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay4Slot3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay4Slot3.setEnabled(false);
        txtDay4Slot3.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay4Slot4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay4Slot4.setEnabled(false);
        txtDay4Slot4.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay4Slot5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay4Slot5.setEnabled(false);
        txtDay4Slot5.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay4Slot6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay4Slot6.setEnabled(false);
        txtDay4Slot6.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay4Slot7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay4Slot7.setEnabled(false);
        txtDay4Slot7.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay4Slot8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay4Slot8.setEnabled(false);
        txtDay4Slot8.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay4Slot9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay4Slot9.setEnabled(false);
        txtDay4Slot9.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay5Slot2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay5Slot2.setEnabled(false);
        txtDay5Slot2.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay5Slot3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay5Slot3.setEnabled(false);
        txtDay5Slot3.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay5Slot4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay5Slot4.setEnabled(false);
        txtDay5Slot4.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay5Slot5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay5Slot5.setEnabled(false);
        txtDay5Slot5.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay5Slot6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay5Slot6.setEnabled(false);
        txtDay5Slot6.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay5Slot7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay5Slot7.setEnabled(false);
        txtDay5Slot7.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay5Slot8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay5Slot8.setEnabled(false);
        txtDay5Slot8.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay5Slot9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay5Slot9.setEnabled(false);
        txtDay5Slot9.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay6Slot2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay6Slot2.setEnabled(false);
        txtDay6Slot2.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay6Slot3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay6Slot3.setEnabled(false);
        txtDay6Slot3.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay6Slot4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay6Slot4.setEnabled(false);
        txtDay6Slot4.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay6Slot5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay6Slot5.setEnabled(false);
        txtDay6Slot5.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay6Slot6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay6Slot6.setEnabled(false);
        txtDay6Slot6.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay6Slot7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay6Slot7.setEnabled(false);
        txtDay6Slot7.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay6Slot8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay6Slot8.setEnabled(false);
        txtDay6Slot8.setMinimumSize(new java.awt.Dimension(100, 22));

        txtDay6Slot9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDay6Slot9.setEnabled(false);
        txtDay6Slot9.setMinimumSize(new java.awt.Dimension(100, 22));

        javax.swing.GroupLayout jPanelDoctorsAvailabilityLayout = new javax.swing.GroupLayout(jPanelDoctorsAvailability);
        jPanelDoctorsAvailability.setLayout(jPanelDoctorsAvailabilityLayout);
        jPanelDoctorsAvailabilityLayout.setHorizontalGroup(
            jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDoctorsAvailabilityLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDoctorsAvailabilityLayout.createSequentialGroup()
                        .addComponent(txtDaySlot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDoctorsAvailabilityLayout.createSequentialGroup()
                        .addComponent(txtSlot9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay1Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay2Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay3Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay4Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay5Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay6Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay7Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelDoctorsAvailabilityLayout.createSequentialGroup()
                            .addComponent(txtSlot8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDay1Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDay2Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDay3Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDay4Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDay5Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDay6Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDay7Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDoctorsAvailabilityLayout.createSequentialGroup()
                                .addComponent(txtSlot7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay1Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay2Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay3Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay4Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay5Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay6Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay7Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDoctorsAvailabilityLayout.createSequentialGroup()
                                .addComponent(txtSlot6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay1Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay2Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay3Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay4Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay5Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay6Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay7Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDoctorsAvailabilityLayout.createSequentialGroup()
                                .addComponent(txtSlot5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay1Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay2Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay3Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay4Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay5Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay6Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay7Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDoctorsAvailabilityLayout.createSequentialGroup()
                                .addComponent(txtSlot4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay1Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay2Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay3Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay4Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay5Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay6Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay7Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDoctorsAvailabilityLayout.createSequentialGroup()
                                .addComponent(txtSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay1Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay2Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay3Day3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay4Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay5Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay6Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay7Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDoctorsAvailabilityLayout.createSequentialGroup()
                                .addComponent(txtSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay1Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay2Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay3Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay4Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay5Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay6Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay7Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDoctorsAvailabilityLayout.createSequentialGroup()
                                .addComponent(txtSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay1Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay2Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay3Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay4Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay5Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay6Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDay7Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelDoctorsAvailabilityLayout.setVerticalGroup(
            jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDoctorsAvailabilityLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDaySlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDay1Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay2Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay3Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay4Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay5Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay6Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay7Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDay1Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay2Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay3Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay4Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay7Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay5Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay6Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDay1Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay2Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay3Day3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay7Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay4Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay5Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay6Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDay1Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay2Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay3Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay7Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlot4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay4Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay5Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay6Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDay1Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay2Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay3Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay7Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlot5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay4Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay5Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay6Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDay1Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay2Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay3Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay7Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlot6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay4Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay5Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay6Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDay1Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay2Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay3Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay7Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlot7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay4Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay5Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay6Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDay1Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay2Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay3Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay7Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlot8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay4Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay5Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay6Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDoctorsAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDay1Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay2Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay3Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay7Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlot9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay4Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay5Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay6Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelDoctorAvailabilityLayout = new javax.swing.GroupLayout(jPanelDoctorAvailability);
        jPanelDoctorAvailability.setLayout(jPanelDoctorAvailabilityLayout);
        jPanelDoctorAvailabilityLayout.setHorizontalGroup(
            jPanelDoctorAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDoctorsAvailability, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelDoctorAvailabilityLayout.setVerticalGroup(
            jPanelDoctorAvailabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDoctorsAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPanel.addTab("Doctor's Availability", jPanelDoctorAvailability);

        jPanel_About.setBackground(new java.awt.Color(104, 120, 128));

        javax.swing.GroupLayout jPanel_AboutLayout = new javax.swing.GroupLayout(jPanel_About);
        jPanel_About.setLayout(jPanel_AboutLayout);
        jPanel_AboutLayout.setHorizontalGroup(
            jPanel_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
        );
        jPanel_AboutLayout.setVerticalGroup(
            jPanel_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jTabbedPanel.addTab("About", jPanel_About);

        jPanelPharmacy.setBackground(new java.awt.Color(104, 120, 128));

        javax.swing.GroupLayout jPanelPharmacyLayout = new javax.swing.GroupLayout(jPanelPharmacy);
        jPanelPharmacy.setLayout(jPanelPharmacyLayout);
        jPanelPharmacyLayout.setHorizontalGroup(
            jPanelPharmacyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
        );
        jPanelPharmacyLayout.setVerticalGroup(
            jPanelPharmacyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jTabbedPanel.addTab("Pharmacy", jPanelPharmacy);

        jPanelEmergency.setBackground(new java.awt.Color(104, 120, 128));

        javax.swing.GroupLayout jPanelEmergencyLayout = new javax.swing.GroupLayout(jPanelEmergency);
        jPanelEmergency.setLayout(jPanelEmergencyLayout);
        jPanelEmergencyLayout.setHorizontalGroup(
            jPanelEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
        );
        jPanelEmergencyLayout.setVerticalGroup(
            jPanelEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jTabbedPanel.addTab("Emergency", jPanelEmergency);

        jPanelRegistration.setBackground(new java.awt.Color(104, 120, 128));

        btnRegister.setText("Register");

        firstNameTextField.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        firstNameTextField.setText("FIRSTNAME");
        firstNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameTextFieldFocusGained(evt);
            }
        });
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        lastNameTextField.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lastNameTextField.setText("LASTNAME");
        lastNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameTextFieldFocusGained(evt);
            }
        });

        streetAddressLine1TextField.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        streetAddressLine1TextField.setText("Street Address Line 1");
        streetAddressLine1TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                streetAddressLine1TextFieldFocusGained(evt);
            }
        });
        streetAddressLine1TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                streetAddressLine1TextFieldMouseClicked(evt);
            }
        });

        streetAddressLine2TextField.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        streetAddressLine2TextField.setText("Street Address Line 2");
        streetAddressLine2TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                streetAddressLine2TextFieldFocusGained(evt);
            }
        });
        streetAddressLine2TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                streetAddressLine2TextFieldMouseClicked(evt);
            }
        });

        countryTextField.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        countryTextField.setText("Country");
        countryTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                countryTextFieldFocusGained(evt);
            }
        });

        cityTextField.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        cityTextField.setText("City");
        cityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityTextFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistrationLayout = new javax.swing.GroupLayout(jPanelRegistration);
        jPanelRegistration.setLayout(jPanelRegistrationLayout);
        jPanelRegistrationLayout.setHorizontalGroup(
            jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(streetAddressLine1TextField)
                    .addComponent(streetAddressLine2TextField)
                    .addComponent(cityTextField)
                    .addComponent(countryTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrationLayout.createSequentialGroup()
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226)))
                .addContainerGap(358, Short.MAX_VALUE))
        );
        jPanelRegistrationLayout.setVerticalGroup(
            jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrationLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanelRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(streetAddressLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(streetAddressLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(btnRegister)
                .addGap(122, 122, 122))
        );

        jTabbedPanel.addTab("Registration", jPanelRegistration);

        container.add(jTabbedPanel, "card2");

        jSplitPane.setRightComponent(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        //        btnLogin.setVisible(true);
//        SystemAdminJPanel sajp= new SystemAdminJPanel(container);
//        container.add("sajp",sajp);
//        CardLayout layout = (CardLayout) container.getLayout();
//        layout.next(container);

// Get user name
        String userName = txtUserName.getText();
        // Get Password
        char[] passwordCharArray = txtPassword.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the system user account directory if you have the user
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        Network inNetwork = null;
        if (userAccount == null) {
            //Step2: Go inside each network to check each enterprise
            for (Network network : system.getNetworkList()) {
                //Step 2-a: Check against each enterprise
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    if (userAccount == null) {
                        //Step3: Check against each organization inside that enterprise
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                            if (userAccount != null) {
                                inEnterprise = enterprise;
                                inOrganization = organization;
                                inNetwork = network;
                                break;
                            }
                        }
                    } else {
                        inEnterprise = enterprise;
                        inNetwork = network;
                        break;
                    }
                    if (inOrganization != null) {
                        break;
                    }
                }
                if (inEnterprise != null) {
                    break;
                }
            }
        }

        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid Credentails!");
            return;
        } else {
            CardLayout layout = (CardLayout) container.getLayout();
            container.add(userAccount.getRole().toString()+"workArea", userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, system, inNetwork));
            layout.next(container);
        }

        btnLogin.setVisible(false);
        btnLogout.setVisible(true);
        lblUserName.setVisible(false);
        lblPassWord.setVisible(false);
        txtUserName.setVisible(false);
        txtPassword.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        btnLogin.setVisible(true);
        btnLogout.setVisible(false);
        lblUserName.setVisible(true);
        lblPassWord.setVisible(true);
        txtUserName.setVisible(true);
        txtPassword.setVisible(true);
        
        txtUserName.setText("");
        txtPassword.setText("");

        container.removeAll();
        container.add(jTabbedPanel);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusGained
        // TODO add your handling code here:
        txtUserName.setText("");
    }//GEN-LAST:event_txtUserNameFocusGained

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtSlot5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSlot5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSlot5ActionPerformed

    private void txtSlot8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSlot8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSlot8ActionPerformed

    private void txtDay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDay1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtDay1ActionPerformed

    private void firstNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameTextFieldFocusGained
        // TODO add your handling code here:
        firstNameTextField.setText("");
    }//GEN-LAST:event_firstNameTextFieldFocusGained

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void lastNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameTextFieldFocusGained
        // TODO add your handling code here:
        lastNameTextField.setText("");
    }//GEN-LAST:event_lastNameTextFieldFocusGained

    private void streetAddressLine1TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetAddressLine1TextFieldFocusGained
        // TODO add your handling code here:
        streetAddressLine1TextField.setText("");
    }//GEN-LAST:event_streetAddressLine1TextFieldFocusGained

    private void streetAddressLine1TextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_streetAddressLine1TextFieldMouseClicked
        // TODO add your handling code here:
        streetAddressLine1TextField.setText("");
    }//GEN-LAST:event_streetAddressLine1TextFieldMouseClicked

    private void streetAddressLine2TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetAddressLine2TextFieldFocusGained
        // TODO add your handling code here:
        streetAddressLine2TextField.setText("");
    }//GEN-LAST:event_streetAddressLine2TextFieldFocusGained

    private void streetAddressLine2TextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_streetAddressLine2TextFieldMouseClicked
        // TODO add your handling code here:
        streetAddressLine2TextField.setText("");
    }//GEN-LAST:event_streetAddressLine2TextFieldMouseClicked

    private void countryTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryTextFieldFocusGained
        // TODO add your handling code here:
        countryTextField.setText("");
    }//GEN-LAST:event_countryTextFieldFocusGained

    private void cityTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityTextFieldFocusGained
        // TODO add your handling code here:
        cityTextField.setText("");
    }//GEN-LAST:event_cityTextFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JPanel container;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel jPanelDoctorAvailability;
    private javax.swing.JPanel jPanelDoctorsAvailability;
    private javax.swing.JPanel jPanelEmergency;
    private javax.swing.JPanel jPanelPharmacy;
    private javax.swing.JPanel jPanelRegistration;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPanel jPanel_About;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTabbedPane jTabbedPanel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassWord;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField streetAddressLine1TextField;
    private javax.swing.JTextField streetAddressLine2TextField;
    private javax.swing.JTextField txtDay1;
    private javax.swing.JTextField txtDay1Slot1;
    private javax.swing.JTextField txtDay1Slot2;
    private javax.swing.JTextField txtDay1Slot3;
    private javax.swing.JTextField txtDay1Slot4;
    private javax.swing.JTextField txtDay1Slot5;
    private javax.swing.JTextField txtDay1Slot6;
    private javax.swing.JTextField txtDay1Slot7;
    private javax.swing.JTextField txtDay1Slot8;
    private javax.swing.JTextField txtDay1Slot9;
    private javax.swing.JTextField txtDay2;
    private javax.swing.JTextField txtDay2Slot1;
    private javax.swing.JTextField txtDay2Slot2;
    private javax.swing.JTextField txtDay2Slot3;
    private javax.swing.JTextField txtDay2Slot4;
    private javax.swing.JTextField txtDay2Slot5;
    private javax.swing.JTextField txtDay2Slot6;
    private javax.swing.JTextField txtDay2Slot7;
    private javax.swing.JTextField txtDay2Slot8;
    private javax.swing.JTextField txtDay2Slot9;
    private javax.swing.JTextField txtDay3;
    private javax.swing.JTextField txtDay3Day3;
    private javax.swing.JTextField txtDay3Slot1;
    private javax.swing.JTextField txtDay3Slot2;
    private javax.swing.JTextField txtDay3Slot4;
    private javax.swing.JTextField txtDay3Slot5;
    private javax.swing.JTextField txtDay3Slot6;
    private javax.swing.JTextField txtDay3Slot7;
    private javax.swing.JTextField txtDay3Slot8;
    private javax.swing.JTextField txtDay3Slot9;
    private javax.swing.JTextField txtDay4;
    private javax.swing.JTextField txtDay4Slot1;
    private javax.swing.JTextField txtDay4Slot2;
    private javax.swing.JTextField txtDay4Slot3;
    private javax.swing.JTextField txtDay4Slot4;
    private javax.swing.JTextField txtDay4Slot5;
    private javax.swing.JTextField txtDay4Slot6;
    private javax.swing.JTextField txtDay4Slot7;
    private javax.swing.JTextField txtDay4Slot8;
    private javax.swing.JTextField txtDay4Slot9;
    private javax.swing.JTextField txtDay5;
    private javax.swing.JTextField txtDay5Slot1;
    private javax.swing.JTextField txtDay5Slot2;
    private javax.swing.JTextField txtDay5Slot3;
    private javax.swing.JTextField txtDay5Slot4;
    private javax.swing.JTextField txtDay5Slot5;
    private javax.swing.JTextField txtDay5Slot6;
    private javax.swing.JTextField txtDay5Slot7;
    private javax.swing.JTextField txtDay5Slot8;
    private javax.swing.JTextField txtDay5Slot9;
    private javax.swing.JTextField txtDay6;
    private javax.swing.JTextField txtDay6Slot1;
    private javax.swing.JTextField txtDay6Slot2;
    private javax.swing.JTextField txtDay6Slot3;
    private javax.swing.JTextField txtDay6Slot4;
    private javax.swing.JTextField txtDay6Slot5;
    private javax.swing.JTextField txtDay6Slot6;
    private javax.swing.JTextField txtDay6Slot7;
    private javax.swing.JTextField txtDay6Slot8;
    private javax.swing.JTextField txtDay6Slot9;
    private javax.swing.JTextField txtDay7;
    private javax.swing.JTextField txtDay7Slot1;
    private javax.swing.JTextField txtDay7Slot2;
    private javax.swing.JTextField txtDay7Slot3;
    private javax.swing.JTextField txtDay7Slot4;
    private javax.swing.JTextField txtDay7Slot5;
    private javax.swing.JTextField txtDay7Slot6;
    private javax.swing.JTextField txtDay7Slot7;
    private javax.swing.JTextField txtDay7Slot8;
    private javax.swing.JTextField txtDay7Slot9;
    private javax.swing.JTextField txtDaySlot;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSlot1;
    private javax.swing.JTextField txtSlot2;
    private javax.swing.JTextField txtSlot3;
    private javax.swing.JTextField txtSlot4;
    private javax.swing.JTextField txtSlot5;
    private javax.swing.JTextField txtSlot6;
    private javax.swing.JTextField txtSlot7;
    private javax.swing.JTextField txtSlot8;
    private javax.swing.JTextField txtSlot9;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
