/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.DoctorRole;

import business.UserAccount.UserAccount;
import business.WorkQueue.Schedule;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ketul
 */
public class DoctorModifySchedule extends javax.swing.JPanel {

    /**
     * Creates new form DoctorUpdateSchedule
     */
    JPanel container;
    UserAccount useraccount;
    Schedule schedule;
    public DoctorModifySchedule(JPanel container, UserAccount userAccount, Schedule schedule) {
        initComponents();    
        this.container = container;
        this.useraccount = userAccount;
        this.schedule = schedule;
        populateSchedule();
        btnSaveSchedule.setEnabled(false);
        btnModifySchedule.setEnabled(true);
    }
    
    private void populateSchedule()
    {
        txtDate.setDate(schedule.getDate());
        txtHours.setText(String.valueOf(schedule.getAvailHours()));
        txtLocation.setText(schedule.getLocation());
        txtTime.setText(schedule.getTime());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        hoursLabel = new javax.swing.JLabel();
        txtHours = new javax.swing.JTextField();
        locationLabel = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        btnSaveSchedule = new javax.swing.JButton();
        btnModifySchedule = new javax.swing.JButton();
        banner = new javax.swing.JLabel();
        txtDate = new org.jdesktop.swingx.JXDatePicker();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(104, 120, 128));

        dateLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLabel.setText("Date:");

        timeLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeLabel.setText("Time:");

        txtTime.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtTime.setEnabled(false);
        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });

        hoursLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        hoursLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hoursLabel.setText("Hours:");

        txtHours.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtHours.setEnabled(false);

        locationLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        locationLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        locationLabel.setText("Location:");

        txtLocation.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtLocation.setEnabled(false);

        btnSaveSchedule.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSaveSchedule.setText("Save Schedule");
        btnSaveSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveScheduleActionPerformed(evt);
            }
        });

        btnModifySchedule.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnModifySchedule.setText("Modify Schedule");
        btnModifySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyScheduleActionPerformed(evt);
            }
        });

        banner.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        banner.setText("Modify Schedule");

        txtDate.setEnabled(false);

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banner)
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(locationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTime)
                    .addComponent(txtLocation)
                    .addComponent(txtHours)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(btnSaveSchedule)
                .addGap(49, 49, 49)
                .addComponent(btnModifySchedule)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banner)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursLabel)
                    .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveSchedule)
                    .addComponent(btnModifySchedule))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void btnModifyScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyScheduleActionPerformed
        // TODO add your handling code here:
        btnModifySchedule.setEnabled(false);
        txtDate.setEnabled(true);
        txtHours.setEnabled(true);
        txtLocation.setEnabled(true);
        txtTime.setEnabled(true);
        btnSaveSchedule.setEnabled(true);
    }//GEN-LAST:event_btnModifyScheduleActionPerformed

    private void btnSaveScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveScheduleActionPerformed
        // TODO add your handling code here:
        schedule.setAvailHours(Float.parseFloat((txtHours.getText())));
        schedule.setDate(txtDate.getDate());
        schedule.setLocation(txtLocation.getText());
        schedule.setTime(txtTime.getText());
        btnModifySchedule.setEnabled(true);
        btnSaveSchedule.setEnabled(false);
        txtDate.setEnabled(false);
        txtHours.setEnabled(false);
        txtLocation.setEnabled(false);
        txtTime.setEnabled(false);
    }//GEN-LAST:event_btnSaveScheduleActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnModifySchedule;
    private javax.swing.JButton btnSaveSchedule;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel hoursLabel;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel timeLabel;
    private org.jdesktop.swingx.JXDatePicker txtDate;
    private javax.swing.JTextField txtHours;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
